local z = {
  bg_transparent = 'NONE',
  fg_blue = '#2ac3de',
  fg_vscode = '#fff7f2',
  bg_vscode = '#007acc',
}
return {
  normal = {
    a = { fg = z.fg_vscode, bg = z.bg_vscode },
    b = { fg = z.fg_vscode, bg = z.bg_vscode },
    c = { fg = z.fg_vscode, bg = z.bg_vscode },
    x = { fg = z.fg_vscode, bg = z.bg_vscode },
    y = { fg = z.fg_vscode, bg = z.bg_vscode },
    z = { fg = z.fg_vscode, bg = z.bg_vscode },
  },
  insert = {
    a = { fg = z.fg_vscode, bg = z.bg_vscode },
    b = { fg = z.fg_vscode, bg = z.bg_vscode },
    c = { fg = z.fg_vscode, bg = z.bg_vscode },
    x = { fg = z.fg_vscode, bg = z.bg_vscode },
    y = { fg = z.fg_vscode, bg = z.bg_vscode },
    z = { fg = z.fg_vscode, bg = z.bg_vscode },
  },
  visual = {
    a = { fg = z.fg_vscode, bg = z.bg_vscode },
    b = { fg = z.fg_vscode, bg = z.bg_vscode },
    c = { fg = z.fg_vscode, bg = z.bg_vscode },
    x = { fg = z.fg_vscode, bg = z.bg_vscode },
    y = { fg = z.fg_vscode, bg = z.bg_vscode },
    z = { fg = z.fg_vscode, bg = z.bg_vscode },
  },
  command = {
    a = { fg = z.fg_vscode, bg = z.bg_vscode },
    b = { fg = z.fg_vscode, bg = z.bg_vscode },
    c = { fg = z.fg_vscode, bg = z.bg_vscode },
    x = { fg = z.fg_vscode, bg = z.bg_vscode },
    y = { fg = z.fg_vscode, bg = z.bg_vscode },
    z = { fg = z.fg_vscode, bg = z.bg_vscode },
  },
  replace = {
    a = { fg = z.fg_vscode, bg = z.bg_vscode },
    b = { fg = z.fg_vscode, bg = z.bg_vscode },
    c = { fg = z.fg_vscode, bg = z.bg_vscode },
    x = { fg = z.fg_vscode, bg = z.bg_vscode },
    y = { fg = z.fg_vscode, bg = z.bg_vscode },
    z = { fg = z.fg_vscode, bg = z.bg_vscode },
  },
  inactive = {
    a = { fg = z.fg_vscode, bg = z.bg_vscode },
    b = { fg = z.fg_vscode, bg = z.bg_vscode },
    c = { fg = z.fg_vscode, bg = z.bg_vscode },
    x = { fg = z.fg_vscode, bg = z.bg_vscode },
    y = { fg = z.fg_vscode, bg = z.bg_vscode },
    z = { fg = z.fg_vscode, bg = z.bg_vscode },
  },
}
