require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.treesitter")
require("user.colorscheme")
require("user.lualine")
require("user.impatient")
require("user.autocommands")
