name: ci

on:
  push:
    branches:
      - lsp
      - lazy

  pull_request:
    branches:
      - lsp
      - lazy

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Stylua
        uses: JohnnyMorganz/stylua-action@v1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .
